INSERT INTO social_network_posts (post_date, author, content, view_count)
VALUES (CURRENT_DATE(), 'A', 'Post Content', 1),
       (CURRENT_DATE(), 'B', 'Post Content.', 11214),
       (CURRENT_DATE(), 'A', 'Post Content.', 456),
       (CURRENT_DATE(), 'B', 'Post Content.', 789),
       (CURRENT_DATE(), 'A', 'Post Content.', 789),
       (CURRENT_DATE(), 'B', 'Post Content.', 5780),
       (CURRENT_DATE(), 'C', 'Post Content.', 456),
       (CURRENT_DATE(), 'B', 'Post Content.', 67),
       (CURRENT_DATE(), 'C', 'Post Content.', 678678),
       (CURRENT_DATE(), 'B', 'Post Content.', 678),
       (CURRENT_DATE(), 'A', 'Post Content.', 567860),
       (CURRENT_DATE(), 'D', 'Post Content.', 5880),
       (CURRENT_DATE(), 'D', 'Post Content.', 76788),
       (CURRENT_DATE(), 'D', 'Post Content.', 56780),
       (CURRENT_DATE(), 'D', 'Post Content.', 56780);
